version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_PORT: "5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

  api-native:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500M'

  api-jvm:
    build:
      dockerfile: Dockerfile.jvm
    env_file:
      - .env
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500M'
