version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_PORT: "5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres